### ISSUE TITLE
Error ExpressionChangedAfterItHasBeenCheckedError on render board

### ISSUE THREAD

**Issue by dimmykarson** [grzegorz103/ngx-chess-board#203]
When I try to render a board in an angular 13 project with material design the following error occurs:

`core.mjs:6500 ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'transform': 'translate3d(NaNpx, NaNpx,0px)'. Current value: 'translate3d(0px, 62.5px,0px)'.. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:6748:11)
    at bindingUpdated (core.mjs:12724:17)
    at checkStylingProperty (core.mjs:16465:32)
    at Module.ɵɵstyleProp (core.mjs:16354:5)
    at NgxChessBoardComponent_div_3_Template (ngx-chess-board.mjs:3028:1866)
    at executeTemplate (core.mjs:9633:9)
    at refreshView (core.mjs:9499:13)
    at refreshEmbeddedViews (core.mjs:10624:17)
    at refreshView (core.mjs:9523:9)
    at refreshComponent (core.mjs:10670:13)`

**Comment by ahamedzoha** [comment]
Experiencing the same error
